site_name: Software de Notas Estudantis
site_url: https://software-de-notas-estudantis.com/
nav: 
- Sobre: index.md
- Modelagem: casosdeuso.md
- Protótipo: prototype.md

theme:
 name: material
 palette:
   primary: indigo
   secondary: amber
   accent: amber
 logo: assets/fepilogoph3.jpeg
 favicon: assets/fepilogoph3.jpeg
 icon: assets/fepilogoph3.jpeg
 top: assets/fepilogoph3.jpeg
 menu: assets/fepilogoph3.jpeg
 extra:
   homepage: assets/fepilogoph3.jpeg